version: '2'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      # disable X-Pack
      # see https://www.elastic.co/guide/en/x-pack/current/xpack-settings.html
      #     https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html#xpack-enabling
      xpack.security.enabled: "false"
      xpack.monitoring.enabled: "false"
      xpack.graph.enabled: "false"
      xpack.watcher.enabled: "false"
    networks:
      - elk
    volumes: 
      - ./esdata:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    expose:
      - "5514"
    networks: 
      - elk
    depends_on:
      - elasticsearch

  logspout:
    command: "-c '/bin/logspout syslog://logstash:5514'"
    entrypoint: /bin/sh
    image: 'gliderlabs/logspout:latest'
    environment: 
      SYSLOG_FORMAT: rfc3164
    depends_on:
      - logstash
    networks:
      - elk
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.2
    environment: 
      LOGSPOUT: ignore
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    networks: 
      - elk
    depends_on:
      - elasticsearch

  nginx:
    image: nginx:alpine
    environment: 
      LOGSPOUT: ignore
    volumes:
      - ./nginx/passwords:/etc/nginx/passwords
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/config/nginx-site.conf:/etc/nginx/conf.d/default.conf 
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana
    ports:
      - "5601:5601"
      - "9200:9200"

networks: 

  elk:
    driver: bridge
